In [ ]:
# KITA CUMA PAKAI NUMPY YA GUYS YAK, ga pakai training data
import numpy as np

In [7]:
def get_dist(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    centered = b - a
    dist = np.sqrt(np.sum(np.pow(centered, 2)))
    return dist

# test
print(get_dist(np.array([1, 2]), np.array([4, 6])) == 5.0)
print(get_dist(np.array([-2, 3]), np.array([2, -1])) == 4 * np.sqrt(2))
print(get_dist(np.array([0, 0]), np.array([5, 12])) == 13)

True
True
True


In [14]:
def get_angle(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> np.float64: # b nya sudutnya dicari
    A = get_dist(b, c)
    B = get_dist(a, c)
    C = get_dist(a, b)

    res_angle = np.arccos( (np.pow(A, 2) + np.pow(C, 2) - np.pow(B, 2)) / (2 * A * C) ) / np.pi * 180
    return res_angle

# Case 1 == 90 derajat
print(get_angle(np.array([1,0]), np.array([0,0]), np.array([0,1])))

# Case 2 == 45 derajat
print(get_angle(np.array([1,0]), np.array([0,0]), np.array([1,1])))

# Case 3 == 180 derajat
print(get_angle(np.array([-1,0]), np.array([0,0]), np.array([1,0])))

90.00000000000001
44.999999999999986
180.0


Kode di bawah hanya untuk jika semua sudut < 120 derajat

In [16]:
def get_equil_height(a: np.ndarray, b: np.ndarray) -> np.float64:
    dist = get_dist(a, b)

    res_equil_height = dist / 2 * np.sqrt(3)
    return res_equil_height

# case 1 == 1.732
print(get_equil_height(np.array([0, 0]), np.array([2, 0])))

# case 2 == 4.330
print(get_equil_height(np.array([1, 1]), np.array([4, 5])))

# case 3 == 2.598
print(get_equil_height(np.array([-2, -1]), np.array([1, -1])))

1.7320508075688772
4.330127018922193
2.598076211353316


In [18]:
def get_center(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    res_center = (a + b) / 2
    return res_center

# case 1 == [1.0, 0.0]
print(get_center(np.array([0, 0]), np.array([2, 0])))

# case 2 == [2.5, 3.0]
print(get_center(np.array([1, 1]), np.array([4, 5])))

# case 3 == [-0.5, -1.0]
print(get_center(np.array([-2, -1]), np.array([1, -1])))

[1. 0.]
[2.5 3. ]
[-0.5 -1. ]


In [20]:
def normalize(a: np.ndarray):
    res_norm = a / get_dist(np.array([0, 0]), a)
    return res_norm

# case 1 == [1.0, 0.0]
print(normalize(np.array([5, 0])))

# case 2 == [0.6, 0.8]
print(normalize(np.array([3, 4])))

# case 3 == [-0.7071, -0.7071]
print(normalize(np.array([-2, -2])))

[1. 0.]
[0.6 0.8]
[-0.70710678 -0.70710678]


In [21]:
def get_dir_vec(a: np.ndarray, b: np.ndarray) -> np.ndarray: # dari a ke b
    centered_vec = b - a

    result_dir = normalize(centered_vec)
    return result_dir

# case 1 == [1.0, 0.0]
print(get_dir_vec(np.array([0, 0]), np.array([5, 0])))

# case 2 == [0.6, 0.8]
print(get_dir_vec(np.array([1, 1]), np.array([4, 5])))

# case 3 == [-0.7071, -0.7071]
print(get_dir_vec(np.array([1, 1]), np.array([-1, -1])))

[1. 0.]
[0.6 0.8]
[-0.70710678 -0.70710678]


In [23]:
def rotate_90_deg(a: np.ndarray) -> np.ndarray: # ini berlawanan arah jarum jam
    a[0], a[1] = -a[1], a[0]
    return a

# case 1 == [0.0, 1.0]
print(rotate_90_deg(np.array([1.0, 0.0])))

# case 2 == [-1.0, 0.0]
print(rotate_90_deg(np.array([0.0, 1.0])))

# case 3 == [1.0, -2.0]
print(rotate_90_deg(np.array([2.0, 1.0])))

[-0.  1.]
[-1.  0.]
[-1.  2.]


In [25]:
def equil_point_two_cases(a: np.ndarray, b: np.ndarray) -> np.ndarray: # 2D array
    if b[0] < a[0]:
        a, b = b, a
    
    center = get_center(a, b)

    dir = get_dir_vec(a, b)
    dir_rotated_90_deg = rotate_90_deg(dir)

    equil_height = get_equil_height(a, b)

    # DUA KASUS
    # case 1
    case_1 = center + (dir_rotated_90_deg * equil_height)
    # case 2
    case_2 = center + (-dir_rotated_90_deg * equil_height)

    return np.array([case_1, case_2])

# case 1 == [[1.0, 1.732], [1.0, -1.732]]
print(equil_point_two_cases(np.array([0, 0]), np.array([2, 0])))

# case 2 == [[-0.964, 5.598], [5.964, 0.402]]
print(equil_point_two_cases(np.array([1, 1]), np.array([4, 5])))

# case 3 == [[-0.5, 1.598], [-0.5, -3.598]]
print(equil_point_two_cases(np.array([-2, -1]), np.array([1, -1])))

[[ 1.          1.73205081]
 [ 1.         -1.73205081]]
[[-0.96410162  5.59807621]
 [ 5.96410162  0.40192379]]
[[-0.5         1.59807621]
 [-0.5        -3.59807621]]


In [27]:
def equil_opposite_point(a: np.ndarray, b: np.ndarray, c: np.ndarray) -> np.ndarray: # b adalah titik fokus, mengcover collinear juga
    two_cases = equil_point_two_cases(a, c)

    # jarak dua kasus terhadap b dan pilih paling besar
    dist_1 = get_dist(b, two_cases[0])
    dist_2 = get_dist(b, two_cases[1])

    if dist_1 > dist_2:
        return two_cases[0]
    else:
        return two_cases[1]
    
# case 1 == [1.0, -1.732]
print(equil_opposite_point(
    np.array([0, 0]),
    np.array([1, 2]),   # b
    np.array([2, 0])
))

# case 2 == [5.964, 0.402]
print(equil_opposite_point(
    np.array([1, 1]),
    np.array([0, 5]),   # b
    np.array([4, 5])
))

# case 3 == [-0.5, -3.598]
print(equil_opposite_point(
    np.array([-2, -1]),
    np.array([0, 2]),   # b
    np.array([1, -1])
))

[ 1.         -1.73205081]
[5.96410162 0.40192379]
[-0.5        -3.59807621]


In [30]:
def get_line_eq(a: np.ndarray, b: np.ndarray) -> np.ndarray: # dengan format [m, b], m adalah gradien dan b adalah y intersection
    slope = (b[1] - a[1]) / (b[0] - a[0])
    bias = a[1] - slope * a[0]

    return np.array([slope, bias])

# case 1 == [1.0, 0.0]
print(get_line_eq(np.array([0, 0]), np.array([2, 2])))

# case 2 == [2.0, 1.0]
print(get_line_eq(np.array([1, 3]), np.array([3, 7])))

# case 3 == [-1.0, 2.0]
print(get_line_eq(np.array([0, 2]), np.array([2, 0])))

[1. 0.]
[2. 1.]
[-1.  2.]


In [33]:
def solve_two_lines(a: np.ndarray, b: np.ndarray, c: np.ndarray, d: np.ndarray) -> np.ndarray:
    line_1 = get_line_eq(a, b)
    line_2 = get_line_eq(c, d)

    x_res = (line_1[1] - line_2[1]) / (line_2[0] - line_1[0])
    y_res = line_1[0] * x_res + line_1[1]

    return np.array([x_res, y_res])

# case 1 == [1.0, 1.0]
print(solve_two_lines(
    np.array([0, 0]), np.array([2, 2]),
    np.array([0, 2]), np.array([2, 0])
))

# case 2 == [2.0, 3.0]
print(solve_two_lines(
    np.array([1, 1]), np.array([3, 5]),
    np.array([0, 3]), np.array([4, 3])
))

# case 3 == [0.5, 1.5]
print(solve_two_lines(
    np.array([0, 1]), np.array([2, 3]),
    np.array([0, 2]), np.array([2, 0])
))

[1. 1.]
[2. 3.]
[0.5 1.5]


In [ ]:
def get_minimum_distance(row):
    coords = np.array([
        [row['X1'], row['Y1']],
        [row['X2'], row['Y2']],
        [row['X3'], row['Y3']]
    ])
    a, b, c = coords[0, :], coords[1, :], coords[2, :]
    A, B, C = get_angle(b, a, c), get_angle(a, b, c), get_angle(a, c, b)

    if A >= 120.0:
        return get_dist(a, b) + get_dist(a, c)
    elif B >= 120.0:
        return get_dist(b, a) + get_dist(b, c)
    elif C >= 120.0:
        return get_dist(c, a) + get_dist(c, b)
    
    ext_a = equil_opposite_point(b, a, c)
    ext_b = equil_opposite_point(a, b, c)

    fermat_point = solve_two_lines(a, ext_a, b, ext_b)

    final_distance = get_dist(fermat_point, a) + get_dist(fermat_point, b) + get_dist(fermat_point, c)
    return final_distance

# case 1 == 2.0  (collinear, middle point optimal)
row = {'X1': 0, 'Y1': 0, 'X2': 1, 'Y2': 0, 'X3': 2, 'Y3': 0}
print(get_minimum_distance(row))

# case 2 == 3.464  (equilateral triangle, Fermat point center)
row = {'X1': 0, 'Y1': 0, 'X2': 2, 'Y2': 0, 'X3': 1, 'Y3': 1.732}
print(get_minimum_distance(row))

# case 3 == 4.007
row = {'X1': 0, 'Y1': 0, 'X2': 4, 'Y2': 0, 'X3': 1, 'Y3': 0.1}
print(get_minimum_distance(row))

2.0
3.464050807568877
4.006653766072816
